[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Required for Next.js 13+ with app directory
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes - proxy API requests to your backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Required for client-side routing in Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.jitsi.net https://*.jitsi.org; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com data:; connect-src 'self' https: wss:; media-src 'self' https:; frame-src 'self' https://*.jitsi.net;"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  # Local development command
  command = "npm run dev"
  port = 3000
  publish = ".next"
  targetPort = 3000

[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_APP_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_APP_ENV = "staging"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_APP_ENV = "staging"

# Required environment variables (these should be set in Netlify UI)
# [build.environment]
#   NEXT_PUBLIC_JITSI_APP_ID = "your-jitsi-app-id"
#   NEXT_PUBLIC_JITSI_DOMAIN = "meet.jit.si"
#   NEXT_PUBLIC_DFX_NETWORK = "ic"
#   NEXT_PUBLIC_INTERNET_IDENTITY_URL = "https://identity.ic0.app"
#   NEXT_PUBLIC_IC_HOST = "https://ic0.app"
